version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: orders
  app:
    build: .
    command: make start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:mypass@db/orders
    depends_on:
      - db
